name: Deploy PR previews
concurrency: preview-${{ github.ref }}
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed
jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - run: npm i && npm run build
        if: github.event.action != 'closed'
      - uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: .
          preview-branch: gh-pages
          umbrella-dir: pr-preview
          action: auto
          
      - name: Delete umbrella directory
        if: github.event.action == 'closed'
        run: |
          git fetch origin gh-pages
          git worktree add --track -b gh-pages origin/gh-pages
          rm -rf pr-preview
          git add .
          git commit -m "Delete umbrella directory for PR #${{ github.event.pull_request.number }}"
          git push origin gh-pages
          git worktree remove gh-pages

permissions:
  contents: write
  pull-requests: write